---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{r}
knitr::opts_chunk$set(cache = TRUE)

library(readr)
library(magrittr)
setwd("/Users/ashipunova/work/data_science_coursera/intro_r/RepData_PeerAssessment1/")
```

## Loading and preprocessing the data
```{r}
# unzip("sales.zip", list = TRUE)
activity_data <- readr::read_csv(unzip("activity.zip", "activity.csv"))

str(activity_data)
# transform(activity_data, date = ymd(date))

```


## What is mean total number of steps taken per day?

```{r}
# aggregate(steps ~ date, activity_data, mean, na.rm = T)
sums <- aggregate(x = activity_data$steps,                # Specify data column
  by = list(activity_data$date),              # Specify group indicator
  FUN = sum)                            # Specify function (i.e. sum)
tot_by2 <- aggregate(steps ~ date, activity_data, mean, na.rm = T)
aggregate(x = activity_data$steps,                # Specify data column
  by = list(activity_data$date),              # Specify group indicator
  FUN = mean, na.rm = T)                            # Specify function (i.e. sum)


```

## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
